---
- name: Check for Python
  raw: ls -l /usr/bin/python*
  changed_when: false
  failed_when: false
  register: check_python

- name: Gather facts about target host
  setup:
    filter:
      - 'ansible_distribution'

- name: Install nginx
  include_tasks: nginx-{{ ansible_distribution }}.yml
