---
- name: Check target host for Python
  raw: ls -l /usr/bin/python*
  failed_when: false
  register: check_python
  changed_when: check_python.rc != 0

- name: Preconfigure system
  include_tasks: preconfig.yml
  when: check_python.rc != 0

- name: Gather facts about target host
  setup:
    filter:
      - 'ansible_distribution'

- name: Install nginx
  include_tasks: nginx-{{ ansible_distribution }}.yml

- name: Force notified handlers to run at this point
  meta: flush_handlers

- name: Check for changes in 1-st line of service_state file
  lineinfile:
    path: /opt/service_state
    line: "Seems work"
    state: present
  notify:
    - Service nginx restart
