---
- name: Check target host for Python
  raw: ls -l /usr/bin/python*
  failed_when: false
  register: check_python
  changed_when: check_python.rc != 0

- name: Preconfigure system
  include_tasks: preconfig.yml
  when: check_python.rc != 0

- name: Gather facts about target host
  setup:
    filter:
      - 'ansible_distribution'

- name: Install nginx
  include_tasks: nginx-{{ ansible_distribution }}.yml
