---
- name: Install nginx
  pacman:
    name:
      - nginx
    update_cache: yes
    state: latest
  notify:
    - Copy file to target machine
    - Copy nginx configuration in place
    - Service nginx restart
    - Install cronie
    - Start and enable cronie
    - Add cron job
