---
- name: Install EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install nginx
  yum:
    pkg: nginx
    enablerepo: epel
    disable_gpg_check: yes